# OpenAI
OPENAI_API_KEY: ""

# index file
index_file: "index_googledoc.json"
# whisper model size
whisper_model: "base" 
# LLM model 
llm_model: "text-davinci-003"
# embedding model 
embed_model: "text-embedding-ada-002"
# max_input_size
max_input_size: 1000
# num_output
num_output: 200
# text chunk
chunk_size_limit: 200
# overlap
max_chunk_overlap: 0
# top_k search
similarity_top_k: 3