# index file
index_file: "data/index.json"
# whisper model size
whisper_model: "base" 
# LLM model 
llm_model: "text-davinci-003"
# embedding model 
embed_model: "text-embedding-ada-002"
# max_input_size
max_input_size: 3500
# num_output
num_output: 300
# text chunk
chunk_size_limit: 1000
# overlap
max_chunk_overlap: 0
# top_k search
similarity_top_k: 2